description:
  Базовый профиль для головной медицинской организации
elements:
  name:
    description: Полное наименование организации
  alias:
    description: Сокращенное наименование организации
  type:
    description: Тип Организации
    valueset: 
      url: "ru-org-type"
  active:
    description: true для действующих организаций
  identifier:
    description: Идентификаторы организации
    valueset: 
      url: "ru-org-ids"
    minItems: 0
    # elements:
    #   fed-oid:
    #     description: Федеральный OID
    #     elements:
    #       system:
    #         description: urn:CodeSystem:oid
    #   inn:
    #     description: ИНН
    #     elements:
    #       system:
    #         description: urn:identity:inn
    #   ogrn:
    #     description: ОГРН
    #     elements:
    #       system:
    #         description: urn:identity:ogrn
    #   kpp:
    #     description: КПП
    #     elements:
    #       system:
    #         description: urn:identity:kpp
    #   okpo:
    #     description: ОКПО
    #     elements:
    #       system:
    #         description: urn:identity:okpo
    #   okopf:
    #     description: ОКОПФ
    #     elements:
    #       system:
    #         description: urn:identity:okopf
    #   okved:
    #     description: ОКВЭД
    #     elements:
    #       system:
    #         description: urn:identity:okved
    #   fss-number:
    #     description: Рег. номер в ФСС
    #     elements:
    #       system:
    #         description: urn:identity:fss-number
  address:
    description: Адрес организации (фактический и/или почтовый)
    elements:
      legal:
        description: Юридический адрес (для ЮЛ) или адрес места жительства индивидуального предпринимателя для ИП)
        elements:
          extension:
            subject:
              description: Субъекты Российской Федерации
              type: Coding
            fns:
              description: Код региона в ФНС
              type: code
            fias:
              description: Код ФИАС
              type: string
              elements:
                url:
                  description: urn:extension:fias                  
          text: 
            description: Полный почтовый адрес текстом
          type:
            description: postal
